Parameters:
  NameOfService:
    Description: "Name of service this stack is used for"
    Type: String
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0b5eea76982371e91
    us-west-1:
      AMI: ami-00d8a762cb0c50254
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd:[]
              php:[]
          files:
            /var/www/html/index.php:
              content: !Sub |
                <?php print "Hello World";?>
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true
    Properties:
      InstanceType: t2.micro
      ImageId: 
        Fn::FindInMap:
          - RegionMap
          - !Ref AWS::Region
          - AMI
      Tags:
        - Key:  "Name"
          Value: !Ref NameOfService
      SecurityGroups:
        - !Ref MySecurityGroup
      UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource Ec2Instance --region ${AWS::Region}
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from ssh
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
Outputs:
  Website:
    Description: The Public DNS of the website created
    Value: !Sub 'http://${Ec2Instance.PublicDnsName}'